### ISSUE TITLE
 [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)

### ISSUE THREAD

**Issue by kitten77** [gawel/irc3#166]
[venv] % pip install --upgrade irc3
Collecting irc3
  Downloading https://files.pythonhosted.org/packages/d6/b9/59d44b70ec7ff959a9c9e3225194d9463e6f01d3870e519f1c4c23875729/irc3-1.1.0-py3-none-any.whl (162kB)
    100% |################################| 163kB 8.2MB/s 
Requirement already satisfied, skipping upgrade: docopt in ./venv/lib/python3.6/site-packages (from irc3) (0.6.2)
Requirement already satisfied, skipping upgrade: venusian>=1.0 in ./venv/lib/python3.6/site-packages (from irc3) (1.1.0)
Installing collected packages: irc3
  Found existing installation: irc3 1.0.2
    Uninstalling irc3-1.0.2:
      Successfully uninstalled irc3-1.0.2
Successfully installed irc3-1.1.0
[venv] % irc3 config.ini
ERROR irc3.gitty [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:777)
Traceback (most recent call last):
  File "/usr/home/git/git_bot/venv/lib/python3.6/site-packages/irc3/__init__.py", line 161, in connection_made
    transport, protocol = f.result()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 803, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 829, in _create_connection_transport
    yield from waiter
  File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 501, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/usr/local/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/usr/local/lib/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()

Not sure what is happening here?

**Comment by kitten77** [comment]
Thanks found the error it was a expired cert on the server :1st_place_medal: to me
