### ISSUE TITLE
python 3.10 not supported

### ISSUE THREAD

**Issue by Adsicmes** [gawel/irc3#200]
> (pyOsuIrc) C:\Users\abbey\Documents\Codes\pyOsuIrc>irc3 config.ini               
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\Scripts\irc3.exe\__main__.py", line 7, in <module>
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\site-packages\irc3\__init__.py", line 405, in run
    bot = IrcBot.from_argv(argv, botnet=bots)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\site-packages\irc3\base.py", line 449, in from_argv
    context = cls.from_config(cfg)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\site-packages\irc3\base.py", line 388, in from_config
    context = cls(**cfg)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\site-packages\irc3\__init__.py", line 133, in __init__
    self.queue = Queue(loop=self.loop)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\asyncio\queues.py", line 34, in __init__
    super().__init__(loop=loop)
  File "C:\ProgramData\Miniconda3\envs\pyOsuIrc\lib\asyncio\mixins.py", line 17, in __init__
    raise TypeError(
TypeError: As of 3.10, the *loop* parameter was removed from Queue() since it is no longer necessary

Not supported

**Comment by gawel** [comment]
This was already fixed in master. I've just uploaded a new release on pypi
